CREATE TABLE "AspNetUsers" (
    id                     uuid         NOT NULL,
    user_name              varchar(256) NULL,
    normalized_user_name   varchar(256) NULL,
    email                  varchar(256) NULL,
    normalized_email       varchar(256) NULL,
    email_confirmed        boolean      NOT NULL,
    password_hash          text         NULL,
    security_stamp         text         NULL,
    concurrency_stamp      text         NULL,
    phone_number           text         NULL,
    phone_number_confirmed boolean      NOT NULL,
    two_factor_enabled     boolean      NOT NULL,
    lockout_end            timestamptz  NULL,
    lockout_enabled        boolean      NOT NULL,
    access_failed_count    integer      NOT NULL,
    first_name             varchar(128) NOT NULL,
    last_name              varchar(128) NOT NULL,
    created_at_utc         timestamptz  NOT NULL,
    last_login_at_utc      timestamptz  NULL,

    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE "AspNetRoles" (
    id                uuid         NOT NULL,
    name              varchar(256) NULL,
    normalized_name   varchar(256) NULL,
    concurrency_stamp text         NULL,

    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE "AspNetUserRoles" (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_users FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_roles FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetRoleClaims" (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    role_id     uuid    NOT NULL,
    claim_type  text    NULL,
    claim_value text    NULL,

    CONSTRAINT pk_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_role_claims_roles FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    user_id     uuid    NOT NULL,
    claim_type  text    NULL,
    claim_value text    NULL,

    CONSTRAINT pk_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_user_claims_users FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    login_provider        text NOT NULL,
    provider_key          text NOT NULL,
    provider_display_name text NULL,
    user_id               uuid NOT NULL,

    CONSTRAINT pk_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_user_logins_users FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    user_id        uuid NOT NULL,
    login_provider text NOT NULL,
    name           text NOT NULL,
    value          text NULL,

    CONSTRAINT pk_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_user_tokens_users FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_users_normalized_user_name ON "AspNetUsers" (normalized_user_name);

-- Unique because Identity:User:RequireUniqueEmail is on. Its own check is a read followed by a
-- write, so two concurrent registrations for one address can both pass it; only the index
-- settles that. Leaving it non-unique leans on user_name happening to hold the email.
CREATE UNIQUE INDEX ix_users_normalized_email ON "AspNetUsers" (normalized_email);

CREATE UNIQUE INDEX ix_roles_normalized_name ON "AspNetRoles" (normalized_name);

CREATE INDEX ix_user_roles_role_id ON "AspNetUserRoles" (role_id);

CREATE INDEX ix_role_claims_role_id ON "AspNetRoleClaims" (role_id);

CREATE INDEX ix_user_claims_user_id ON "AspNetUserClaims" (user_id);

CREATE INDEX ix_user_logins_user_id ON "AspNetUserLogins" (user_id);
